### ISSUE TITLE
Separate the responsibilities of task queue polling and task execution

### ISSUE THREAD

**Issue by NickDrouin** [conductor-sdk/conductor-csharp#45]
Would it be possible to separate the responsibilities of task queue polling and task execution?

"As a developer, I want to use Azure or AWS serverless (functions/lambda) to periodically check the task queue and execute registered tasks.  I want to set a periodic timer with the cloud platform to wake my conductor-sdk code and directly call an interface that will check for new work and dispatch the registered tasks."

Some apps will use the scheduler (background worker) which is part of the SDK, others will have their own trigger.

There should be a way to configure-services without the built-in scheduler.

I'd take a crack at it, but it seems there is a refactor already in flight, #37 .

**Comment by gardusig** [comment]
Hi @NickDrouin, can you check if the provided resources below help you to achieve your goal?

The SDK have a few interfaces by `Conductor.Client.Interfaces`, which now contains `WorkflowTaskHttpClient`. By providing a `Configuration`, it instantiates a `TaskResourceApi`, with the required implementation to connect with the server to get tasks from queue and update them.

https://github.com/conductor-sdk/conductor-csharp/blob/31f1941e2e6ca4308ca3348a1d3b1209831b7134/Conductor/Client/Worker/WorkflowTaskHttpClient.cs#L11

The general manager for workers is `WorkflowTaskCoordinator`. Which creates a `WorkflowTaskExecutor` for each worker, with all the implementation required to keep them working :)

It's currently marked as internal but you can still use them through dependency injection. To keep in mind - we recently added batch polling. Which means, we do recommend using since it does not just poll for many tasks, but executes them in parallel.

- Example: https://github.com/conductor-sdk/conductor-csharp/blob/b5ec858ca839e3f19c86719f440e5d78339a3fa6/Tests/Util/WorkerUtil.cs#L13-L16
- Set up server settings: https://github.com/conductor-sdk/conductor-csharp/blob/b5ec858ca839e3f19c86719f440e5d78339a3fa6/Conductor/Client/Worker/WorkflowTaskHost.cs#L16
- Add a worker: https://github.com/conductor-sdk/conductor-csharp/blob/b5ec858ca839e3f19c86719f440e5d78339a3fa6/Conductor/Client/Worker/WorkflowTaskHost.cs#L19

**Comment by v1r3n** [comment]
This is already addressed in the recent release.
